name: build-and-test

on: [workflow_dispatch, push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: make install_deps 

    - name: Configure CMake
      run: make setup_cmake

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Static code analysis
      run: make cppcheck

    - name: Check Clang-format
      run: make check_clang_format
